import { Router } from "express";
import authRoutes from "../modules/auth/auth.route";
import mapsRoutes from '../modules/maps/maps.route';
import ordersRoutes from '../modules/order/order.routes';
import usersRoutes from '../modules/users/user.route';
import dashboardRoutes from "../modules/dashboard/dashboard.route";
import kycRoutes from "../modules/kyc/kyc.route";
import driverDocumentsRoutes from "../modules/driver-documents/driver-documents.route";
import driverVehiclesRoutes from "../modules/driver-vehicles/driver-vehicles.route";
import supportRoutes from "../modules/support/support.route";
import promotionsRoutes from "../modules/promotions/promotions.route";
import refundsRoutes from "../modules/refunds/refunds.route";
import notificationsRoutes from "../modules/notifications/notifications.route";
import incidentsRoutes from "../modules/incidents/incidents.route";
import zonesRoutes from "../modules/zones/zones.route";
import revenueRoutes from "../modules/revenue/revenue.route";
import pricingRoutes from "../modules/pricing/pricing.route";
import faqsRoutes from "../modules/faqs/faqs.route";
import chatRoutes from "../modules/chat/chat.route";
import settingsRoutes from "../modules/settings/settings.route";
import addressesRoutes from "../modules/addresses/addresses.route";
import paymentsRoutes from "../modules/payments/payments.route";
import foodHomeRoutes from "../modules/food-home/food-home.route";
import vehicleTypesRoutes from "../modules/vehicle-types/vehicle-types.route";
import countriesRoutes from "../modules/countries/countries.route";
import driverFundingRoutes from "../modules/driver-funding/driver-funding.route";
import smsTestRoutes from "./sms-test.route";

const router = Router();

router.use("/auth", authRoutes);
router.use('/maps', mapsRoutes);
router.use('/orders', ordersRoutes);
router.use('/users', usersRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/kyc", kycRoutes);
router.use("/driver-documents", driverDocumentsRoutes);
router.use("/driver-vehicles", driverVehiclesRoutes);
router.use("/support", supportRoutes);
router.use("/promotions", promotionsRoutes);
router.use("/refunds", refundsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/incidents", incidentsRoutes);
router.use("/zones", zonesRoutes);
router.use("/revenue", revenueRoutes);
router.use("/pricing", pricingRoutes);
router.use("/faqs", faqsRoutes);
router.use("/chat", chatRoutes);
router.use("/settings", settingsRoutes);
router.use("/addresses", addressesRoutes);
router.use("/payments", paymentsRoutes);
router.use("/food-home", foodHomeRoutes);
router.use("/vehicle-types", vehicleTypesRoutes);
router.use("/countries", countriesRoutes);
router.use("/driver-funding", driverFundingRoutes);
router.use("/sms", smsTestRoutes);

export default router;
